function RTW_rtwnameSIDMap() {
	this.rtwnameHashMap = new Array();
	this.sidHashMap = new Array();
	this.rtwnameHashMap["<Root>"] = {sid: "Increment_Counter"};
	this.sidHashMap["Increment_Counter"] = {rtwname: "<Root>"};
	this.rtwnameHashMap["<Root>/Add"] = {sid: "Increment_Counter:2"};
	this.sidHashMap["Increment_Counter:2"] = {rtwname: "<Root>/Add"};
	this.rtwnameHashMap["<Root>/Add1"] = {sid: "Increment_Counter:10"};
	this.sidHashMap["Increment_Counter:10"] = {rtwname: "<Root>/Add1"};
	this.rtwnameHashMap["<Root>/Constant"] = {sid: "Increment_Counter:1"};
	this.sidHashMap["Increment_Counter:1"] = {rtwname: "<Root>/Constant"};
	this.rtwnameHashMap["<Root>/Constant1"] = {sid: "Increment_Counter:5"};
	this.sidHashMap["Increment_Counter:5"] = {rtwname: "<Root>/Constant1"};
	this.rtwnameHashMap["<Root>/Constant2"] = {sid: "Increment_Counter:9"};
	this.sidHashMap["Increment_Counter:9"] = {rtwname: "<Root>/Constant2"};
	this.rtwnameHashMap["<Root>/Constant3"] = {sid: "Increment_Counter:11"};
	this.sidHashMap["Increment_Counter:11"] = {rtwname: "<Root>/Constant3"};
	this.rtwnameHashMap["<Root>/Constant4"] = {sid: "Increment_Counter:12"};
	this.sidHashMap["Increment_Counter:12"] = {rtwname: "<Root>/Constant4"};
	this.rtwnameHashMap["<Root>/Constant5"] = {sid: "Increment_Counter:13"};
	this.sidHashMap["Increment_Counter:13"] = {rtwname: "<Root>/Constant5"};
	this.rtwnameHashMap["<Root>/Relational Operator"] = {sid: "Increment_Counter:4"};
	this.sidHashMap["Increment_Counter:4"] = {rtwname: "<Root>/Relational Operator"};
	this.rtwnameHashMap["<Root>/Relational Operator1"] = {sid: "Increment_Counter:14"};
	this.sidHashMap["Increment_Counter:14"] = {rtwname: "<Root>/Relational Operator1"};
	this.rtwnameHashMap["<Root>/Scope"] = {sid: "Increment_Counter:6"};
	this.sidHashMap["Increment_Counter:6"] = {rtwname: "<Root>/Scope"};
	this.rtwnameHashMap["<Root>/Scope1"] = {sid: "Increment_Counter:15"};
	this.sidHashMap["Increment_Counter:15"] = {rtwname: "<Root>/Scope1"};
	this.rtwnameHashMap["<Root>/Switch"] = {sid: "Increment_Counter:8"};
	this.sidHashMap["Increment_Counter:8"] = {rtwname: "<Root>/Switch"};
	this.rtwnameHashMap["<Root>/Switch1"] = {sid: "Increment_Counter:16"};
	this.sidHashMap["Increment_Counter:16"] = {rtwname: "<Root>/Switch1"};
	this.rtwnameHashMap["<Root>/Unit Delay"] = {sid: "Increment_Counter:7"};
	this.sidHashMap["Increment_Counter:7"] = {rtwname: "<Root>/Unit Delay"};
	this.rtwnameHashMap["<Root>/Unit Delay1"] = {sid: "Increment_Counter:17"};
	this.sidHashMap["Increment_Counter:17"] = {rtwname: "<Root>/Unit Delay1"};
	this.getSID = function(rtwname) { return this.rtwnameHashMap[rtwname];}
	this.getRtwname = function(sid) { return this.sidHashMap[sid];}
}
RTW_rtwnameSIDMap.instance = new RTW_rtwnameSIDMap();
